import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 128
dimensions.lines = 42
decorations = "Buttonless"
# opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal.family = "DejaVuSansM Nerd Font Mono"
size = 15

[selection]
save_to_clipboard=true

[keyboard]
bindings = [
    { key = "Space", mods = "Control|Command", action = "ToggleViMode" },
]

[scrolling]
history = 100000
